language: go

go: 1.10.x

install:
- gem install github_changelog_generator

before_script:
- source ./.travis/version-generator.sh
- source ./.travis/changelog-git-push.sh

script:
- make build
- make test
- make changelog
- changelog-git-push
- make dist

before_deploy:
- source ./.travis/changelog-extractor.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  body: "$RELEASE_NOTES"
  file_glob: true
  file: dist/docker-volume-glusterfs-${BUILD_VERSION}-*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

notifications:
  email:
    - andre.markwalder@gmail.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/273c2a06c952534253d1
    on_success: change
    on_failure: always
    on_start: never
