language: go

go: 1.10.x

before_script:
  - source ./.travis/version-generator.sh
  - source ./.travis/deploy-changelog.sh

script: 
  - make build
  - make test
  - make dist

after_success:
  - RELEASE=$BUILD_VERSION deploy-changelog
  if: branch =~ \r\e\l\e\a\s\e\-\v[0-9]+\.[0-9]+\.[0-9]+


#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file_glob: true
#  file: dist/docker-volume-glusterfs-${BUILD_VERSION}-*
#  skip_cleanup: true
#  overwrite: true
#  on: $TRAVIS_BRANCH =~ ^release-v[0-9]+\.[0-9]+\.[0-9]+ 



#before_script:
#- source ./.travis/version-generator.sh
#- source ./.travis/deploy-changelog.sh
#
#script:
#- make build
#- make test
#- make dist
#
#after_success:
#- deploy-changelog
#
#deploy:
#  provider: releases
#  api_key: $GITHUB_TOKEN
#  file_glob: true
#  file: dist/docker-volume-glusterfs-${BUILD_VERSION}-*
#  skip_cleanup: true
#  overwrite: true
#  on:
#    tags: true
#
#after_deploy:
#- echo "************* AFTER DEPLOY ***************"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/273c2a06c952534253d1
    on_success: change
    on_failure: always
    on_start: never
