language: go

go: 1.10.x

stages:

  # build & test
  - name: build and test (master)
    if: branch = master
  - name: build and test (release)
    if: branch != master
  
  # deploy
  - name: deploy (master)
    if: branch = master
  - name: deploy (release)
    if: branch != master

jobs:
  include:

#before_script:
#- if [ "${TRAVIS_TAG}" == "" ]; then
#    export VERSION=`git rev-parse --abbrev-ref HEAD`;
#  else
#    export VERSION=${TRAVIS_TAG:1}; 
#  fi;
#  if [ "${VERSION}" == "HEAD" ]; then
#    export VERSION=SNAPSHOT-`git rev-parse HEAD`;
#  fi;
#- export BUILD=`git rev-parse HEAD`

#after_success:
#- unset VERSION BUILD

    - stage: build and test (master)
      script:
      - export VERSION=SNAPSHOT-`git rev-parse --abbrev-ref HEAD`
      - export BUILD=`git rev-parse HEAD`
      - make build
      - make test

    - stage: build and test (release)
      script:
      - export VERSION=${TRAVIS_TAG:1}; 
      - export BUILD=`git rev-parse HEAD`
      - make build
      - make test

    - stage: deploy (master)
      script: make dist-snapshot

    - stage: deploy (release)
      script: make dist-release
