#!/bin/bash

export RELEASE_NOTES=$(cat <<EOF
# Change Log

## [v0.1.4](https://github.com/amarkwalder/docker-volume-glusterfs/tree/v0.1.4) (2018-06-16)
[Full Changelog](https://github.com/amarkwalder/docker-volume-glusterfs/compare/v0.1.3...v0.1.4)

**Fixed bugs:**

- Create, rm mount dir, really remove gluster volume [\#4](https://github.com/amarkwalder/docker-volume-glusterfs/pull/4) ([tcoupin](https://github.com/tcoupin))
- glusterfs-rest url change [\#3](https://github.com/amarkwalder/docker-volume-glusterfs/pull/3) ([tcoupin](https://github.com/tcoupin))


\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*
EOF
)

echo "$RELEASE_NOTES"
